# ----------- CONFIGURABLE START -----------
title:            "Yi Zhao's Home Page"
description:      "Yi Zhao"
url:              https://yizhao1998.github.io # 域名
signoff:          "Yi Zhao" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 9
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         Code
    url:          /code
    external:     false
  - name:         Hardware
    url:          /hardware
    external:     false
  - name:         Record
    url:          /record
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
